name: Test

on: 
  pull_request: {}
  push:
    branches: main
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies with pip
        run: pip install -e .
      - run: pip install pytest
      - run: pytest test
